title: Kunal's Blog
description: A repository for technicians, developers, and technology enthusiasts.
theme: just-the-docs

url: https://shenoikunal.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
